-- AlterTable
ALTER TABLE "Truck" ADD COLUMN     "currentLoadStops" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentLoadVolume" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "currentLoadWeight" DOUBLE PRECISION NOT NULL DEFAULT 0;
